SU-SWS/decanter-react

src/Alert/Alert.js, src/Button/Button.js, src/Button/Button.stories.js, src/GlobalFooter/GlobalFooter.js, src/IdentityBar/IdentityBar.js, src/Logo/Logo.js
=> fixup! stuff.

.github/workflows/run-jest-tests.yml, jest.config.js, package.json
=> ADAPT-000: Automagically run tests

package-lock.json, package.json, src/Container/Container.js, src/Container/Container.levers.js, src/FlexBox/FlexBox.js, src/FlexBox/FlexBox.levers.js, src/FlexBox/FlexBox.stories.js, src/FlexCell/FlexCell.js, src/FlexCell/FlexCell.levers.js, src/FlexCell/FlexCell.stories.js, src/FlexCell/FlexCell.test.js, src/Grid/Grid.js, src/Grid/Grid.levers.js, src/Grid/Grid.stories.js, src/GridCell/GridCell.js, src/GridCell/GridCell.levers.js, src/GridCell/GridCell.stories.js, src/GridCell/GridCell.test.js
- Grid Cell and Flex Cell component
- Likely will add/tweak options, but ready to be added as a first batch
1. Look at Storybook preview (under both Grid Cell, Flex Cell, Grid examples)
1. Look at code
- JIRA ticket
- Other PRs
=> ADAPT-1935: CSS Grid Cell and Flex Cell components

dist/decanter-react.js, dist/decanter-react.modern.js, dist/decanter-react.module.js, dist/decanter-react.umd.js, package-lock.json, src/Container/Container.js, src/Container/Container.stories.js, src/FlexBox/FlexBox.js, src/FlexBox/FlexBox.stories.js, src/Grid/Grid.js, src/Grid/Grid.stories.js
- Allows users to pass through custom props into the top wrapper.
- End of sprint
- Low
1. Read code
2. View preview build stories: container, flex, grid
3. Try out a couple of custom props yourself
- Online giving.
- ADAPT-1811
- https://github.com/SU-SWS/ood_online_giving/pull/14
=> ADAPT-1811: Add props to wrapper element.

.storybook/preview.js, package-lock.json, src/Skiplink/Skiplink.js, src/Skiplink/Skiplink.stories.js, src/Skiplink/Skiplink.test.js, src/index.js
- Add skiplink component
1. Go to Preview build -> Accessibility -> Skiplink and look at the 2 examples.
1. Hit tab after you click inside the frame of the component demo, confirm that the skiplink shows up
1. Look at the HTML code generated, and the code I added to this branch.
- JIRA ticket
- Other PRs
=> ADAPT-2060 - Skip link component

dist/decanter-react.js, dist/decanter-react.modern.js, dist/decanter-react.module.js, dist/decanter-react.umd.js
- `npm run package` to package up Skiplink component - forgot to do in previous PR.
1. Do this
1. Then this
2. Then this
- JIRA ticket
- Other PRs
=> Package up skiplink

dist/decanter-react.js, dist/decanter-react.modern.js, dist/decanter-react.module.js, dist/decanter-react.umd.js, src/Alert/Alert.js, src/DismissButton/DismissButton.stories.js
- A11y tweaks for alerts
- Add screen reader text for Dismiss button so it would read out "dismiss alert" instead of just "dismiss"
- Use heading for labels
1. Look at preview and code
- JIRA ticket
- Other PRs
=> ADAPT-2272: Alerts a11y fixes for Online Giving

package-lock.json, src/FlexBox/FlexBox.js, src/FlexBox/FlexBox.levers.js, src/FlexBox/FlexBox.stories.js, src/FlexCell/FlexCell.js, src/FlexCell/FlexCell.levers.js, src/FlexCell/FlexCell.stories.js, src/Grid/Grid.js, src/Grid/Grid.levers.js, src/Grid/Grid.stories.js, src/GridCell/GridCell.js, src/GridCell/GridCell.levers.js, src/GridCell/GridCell.stories.js, src/Heading/Heading.js, src/Heading/Heading.levers.js, src/Heading/Heading.stories.js
- Refactors components to eliminate dynamic classes
- End of sprint
- 5/10
1. Review the code 
2. Navigate to the preview build and test out the options to make sure they all still work (Flex, Grid, Heading)
3. Pull this branch into saa_alumni and build using the JIT compiler (untested right now)
- OOD Online Giving
- SAA Alumni
- ADAPT-2296
- @jdwjdwjdw FYI. 
=> ADAPT-2296: PurgeCSS Safe Code

src/CtaButton/CtaButton.stories.js, src/CtaLink/CtaLink.stories.js
- Just a few tweaks so the examples work as intended.
- If approve, please merge into your original ADAPT-2436--cta-ref #28 branch :)
- By end of sprint
1. Pull down locally, `nvm use`, `npm run dev`, and check out the Forwardref stories for CTA buttons and CTA Link. Check that the examples work as intended.
- JIRA ticket
- Other PRs
=> ADAPT-2436 Ref stories tweaks

dist/decanter-react.js, dist/decanter-react.modern.js, dist/decanter-react.module.js, dist/decanter-react.umd.js, src/CtaButton/CtaButton.js, src/CtaButton/CtaButton.stories.js, src/CtaLink/CtaLink.js, src/CtaLink/CtaLink.stories.js
- Add ref to CTA Button and CTA Link components
- tbd
- low
1. Review code and confirm that the ref logic is structure the same as the [Button component](https://github.com/SU-SWS/decanter-react/tree/main/src/Button) 
- [ADAPT-2436](https://stanfordits.atlassian.net/browse/ADAPT-2436)
=> ADAPT-2436 Add ref to CTA Button and CTA Link components

src/FlexCell/FlexCell.js, src/Grid/Grid.js, src/GridCell/GridCell.js, src/Heading/Heading.js, src/common/util/intKeys.js
- Converts the keys in an object to integers and leaves the non-integer values as is. 
1. Do this
1. Then this
2. Then this
- JIRA ticket
- Other PRs
=> ADAPT-1771: Convert string keys to ints.

.github/workflows/autorelease.yml, package-lock.json, package.json
- (Edit the above to reflect status)
Adds autorelease Github action. This action:
- Automatically updates the changelog
- Increments the release version (both in package.json and with a git tag) based on Github label. (i.e. patch, minor, major, alpha, beta, rc)
- Runs 'npm run package' and commits any new changes to dist folder.
- Publishes latest package to npm.
- Next 2-3 days
- 3/10. (Process improvement, but nothing urgent or time sensitive).
This one will be a bit tricky to test, as the action is only fired when merging to "main". 
You may need to create a few dummy PRs that make changes to the README file or something along those lines to test the different scenarios. 
1. Create a new pull request, with base branch of "main". 
1. Add one of the following labels: "patch", "minor", …
=> ADAPT-2517: Added autorelease github action.

.github/workflows/autorelease.yml, package-lock.json, package.json
- (Edit the above to reflect status)
- TL;DR - what's this PR for?
1. Do this
1. Then this
2. Then this
- JIRA ticket
- Other PRs
=> ADAPT-2517: Debugging (Switch decanter package to use semantic versioning)

package-lock.json
=> ADAPT-000: Update packages.

package-lock.json
=> ADAPT-000: Update packages... again.

CONTRIBUTING.md, README.md
- Update contribution documentation
- whenever
- low
Review README.md and CONTRIBUTING.md files.
=> ADAPT-000: Update contribution documentation

README.md
=> ADAPT-000: Update README.md

.babelrc, dist/decanter-react.js, dist/decanter-react.modern.js, dist/decanter-react.module.js, dist/decanter-react.umd.js, package-lock.json, package.json
- For patch release
- Fixes umd module compile warnings on prop-types and react-hero-icons
- Whenever
- Low
=> ADAPT-000: Poster release fixup.

.eslintrc, src/Alert/Alert.js, src/Alert/Alert.stories.js
- Cleans up the alert story by removing the setdanger approach. 
- Whenver
- None
1. Review preview build
- JIRA ticket
- Other PRs
=> ADAPT-000: Remove div and setdanger in alert component story.

src/Button/Button.js
- Allow for a developer to pass an object so they can unset classes.
1. Do this
1. Then this
2. Then this
- JIRA ticket
- Other PRs
=> Update Button propTypes

.storybook/stories/Heading.stories.js, package-lock.json, src/Alert/Alert.stories.js, src/Button/Button.stories.js, src/Container/Container.stories.js, src/CtaButton/CtaButton.stories.js, src/CtaLink/CtaLink.stories.js, src/DismissButton/DismissButton.stories.js, src/FlexBox/FlexBox.stories.js, src/FlexCell/FlexCell.stories.js, src/GlobalFooter/GlobalFooter.stories.js, src/GridCell/GridCell.stories.js, src/HeroIcon/HeroIcon.stories.js, src/Label/Label.stories.js, src/LocalFooter/LocalFooter.stories.js, src/Lockup/Lockup.stories.js, src/Logo/Logo.stories.js, src/TextField/TextField.stories.js
- Fixes browser console errors outputted by storyblok.
=> ADAPT-000: Fixup Storybook console errors.
